import React from 'react';

const ForecastSection = () => {
  const predictions = [
    { day: 'Monday', temp: '75°F', aqi: 'Low (42)', pollen: 'Low', risk: 'Safe', color: 'text-green-600', bg: 'bg-green-50' },
    { day: 'Tuesday', temp: '82°F', aqi: 'Mod (68)', pollen: 'Moderate', risk: 'Watch', color: 'text-yellow-600', bg: 'bg-yellow-50' },
    { day: 'Wednesday', temp: '89°F', aqi: 'High (124)', pollen: 'High', risk: 'Warning', color: 'text-orange-600', bg: 'bg-orange-50' },
    { day: 'Thursday', temp: '94°F', aqi: 'Extreme (162)', pollen: 'High', risk: 'Danger', color: 'text-rose-600', bg: 'bg-rose-50' },
    { day: 'Friday', temp: '85°F', aqi: 'High (110)', pollen: 'Moderate', risk: 'Warning', color: 'text-orange-600', bg: 'bg-orange-50' },
  ];

  return (
    <div className="animate-fadeIn space-y-6">
      <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200">
        <h2 className="text-2xl font-bold text-slate-800 mb-2">7-Day Asthma Risk Forecast</h2>
        <p className="text-slate-500 mb-8">Generated by Gemini analysis of weather and climate satellite data.</p>
        
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-slate-100">
                <th className="pb-4 font-semibold text-slate-600">Day</th>
                <th className="pb-4 font-semibold text-slate-600">Temp</th>
                <th className="pb-4 font-semibold text-slate-600">AQI</th>
                <th className="pb-4 font-semibold text-slate-600">Pollen</th>
                <th className="pb-4 font-semibold text-slate-600">Risk Level</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {predictions.map((p, i) => (
                <tr key={i} className="hover:bg-slate-50 transition-colors">
                  <td className="py-4 font-bold text-slate-800">{p.day}</td>
                  <td className="py-4 text-slate-600">{p.temp}</td>
                  <td className="py-4 text-slate-600">{p.aqi}</td>
                  <td className="py-4 text-slate-600">{p.pollen}</td>
                  <td className="py-4">
                    <span className={`px-3 py-1 rounded-full text-xs font-bold ${p.bg} ${p.color}`}>
                      {p.risk}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
          <h3 className="font-bold text-slate-800 mb-4 flex items-center gap-2">
            <i className="fas fa-lightbulb text-yellow-500"></i>
            AI Insights for Thursday
          </h3>
          <p className="text-slate-600 text-sm leading-relaxed">
            The predicted temperature spike to 94°F combined with high PM2.5 (AQI 162) creates a high probability of "Ozone Peak" conditions. 
            Asthmatic users are advised to stay indoors between 12:00 PM and 5:00 PM. 
            Keep emergency inhalers accessible.
          </p>
        </div>
        <div className="bg-blue-600 p-6 rounded-2xl text-white shadow-lg">
          <h3 className="font-bold mb-4 flex items-center gap-2">
            <i className="fas fa-bell"></i>
            Proactive Alert System
          </h3>
          <p className="text-blue-100 text-sm mb-4">
            Would you like to receive SMS alerts when risk levels exceed "Moderate" in your area?
          </p>
          <button className="bg-white text-blue-600 px-6 py-2 rounded-xl font-bold hover:bg-blue-50 transition-colors">
            Enable Alerts
          </button>
        </div>
      </div>
    </div>
  );
};

export default ForecastSection;
